### ISSUE TITLE
messing model

### ISSUE THREAD

**Issue by atif-zakaria** [ITE-5th/arabic-ner#2]
i can't find cwlm_lstm_crf.model and .json !

**Comment by atif-zakaria** [comment]
@AhmedNourJamalElDin  any ideas !

**Comment by AhmedNourJamalElDin** [comment]
@atif-zakaria, sorry I don't remember.
please check this [one](https://github.com/LiyuanLucasLiu/LM-LSTM-CRF). it may help.

**Comment by atif-zakaria** [comment]
can i have the embed file !
